feature/WAG-59/readChatRoomList
wagora-chat/wagora-chat-backend pull request #20
Opened 2024-08-02 07:57 UTC by mgstyle97

# 작업 분류
- [x] 기능 추가 (feat)
- [ ] 기능 변경 (update)
- [ ] 버그 수정 (fix)
- [ ] 테스트 코드 작성 (test)
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트 (chore)
- [ ] 기타 사소한 수정 (docs)

# 작업 내용 요약
인증된 사용자가 포함된 채팅방 리스트를 조회하는 API 구현

# 코드 리뷰 참고 사항
Query 를 통한 동적 쿼리 부분 코드 리뷰(각 파라미터의 존재 유무에 따른 조건 추가)

# 관련 자료
[Jira](https://hb-wisoft.atlassian.net/browse/WAG-59?atlOrigin=eyJpIjoiZmU5NTgxYjY3YzBhNDIyM2I3Nzg1MmFhNTYwZWYzN2EiLCJwIjoiaiJ9)

2024-08-05 15:19 UTC, kukjun requested changes
@mgstyle97 
다른 이슈는 개선점 위주라 리팩토링을 하면 문제될 것은 없어보이는데, sql injection을 야기할 수 있는 코드가 있는게 문제가 될 것 같습니다.

해당하는 코드를 작성하신 이유가 있을까요?

2024-08-05 15:19 UTC, kukjun commented on src/domain/chat-room/chat-room.service.ts
> +            });
@mgstyle97 
sql injection을 야기할 수 있는 코드인 것 같습니다.

쿼리 직접 사용이 아니라 orm을 이용하는게 어떨까요?

2024-08-05 15:19 UTC, kukjun commented on src/domain/chat-room/chat-room.controller.ts
> +    }
@mgstyle97 
class-validator, class-transformer를 이용해서 들어오는 시점에, 데이터가 유효성과 데이터 변환을 하는게 좋을 것 같습니다.

service가 members: string을 알기보다, members: string[]로 인지해야 할 것 같고, 이를 위해 class-transformer를 이용하고, name과 members 둘중 한가지 값만 가져야 한다면, class-validator를 이용해서 처리하는게 좋아보입니다.

2024-08-05 15:19 UTC, kukjun commented on src/domain/chat-room/chat-room.service.ts
> +    }
@mgstyle97 
저희가 잡지 못하는 문법 오류가 발생하면, 지금은 InternalServerError 가 아닐까요?

그리고 Prisma Error를 어떻게 처리할것인가로는 한번 논의를 해보시죠.

2024-08-06 13:07 UTC, mgstyle97 commented on src/domain/chat-room/chat-room.service.ts
> +            });
복잡한 조인문과 동적 쿼리 생성을 위해 직접적인 쿼리를 생성하도록 하였습니다.
sql injection 관련햐서는 validation 처리가 필요할거 같군요

2024-08-06 13:08 UTC, mgstyle97 commented on src/domain/chat-room/chat-room.controller.ts
> +    }
커스텀 데코레이타를 통해 확인후 처리하는 로직으로 수정해보겠습니다

2024-08-07 10:01 UTC, SeoYunnn reviewed
수고하셨습니다 !
수정할 부분이 있어 보여, Approve 는 미루도록 하겠습니다 !

2024-08-07 10:01 UTC, SeoYunnn commented on src/domain/chat-room/chat-room.service.ts
> +            });
@mgstyle97 
@kukjun 님과 동일한 의견입니다.
직접 SQL 쿼리를 작성하는 대신 Prisma의 쿼리 빌더를 사용하는 것은 어떨까요 ?
SQL Injection 문제와 코드 가독성도 해결될 것 같습니다.

2024-08-07 10:01 UTC, SeoYunnn commented on src/domain/chat-room/chat-room.service.ts
> +            throw new BadRequestException("Prisma Error", ResponseStatus.CHAT_ROOM_F001);
@mgstyle97 
정확히 Prisma Error 가 무엇을 의미하는지 잘 모르겠습니다.
이 부분에 대해서는 논의할 필요가 있어보입니다.

2024-08-19 14:08 UTC, kukjun approved these changes
👍

2024-08-19 14:10 UTC, kukjun commented
@mgstyle97 
leak은 지금 발생하지는 않으니 냅두고 또 발생하면 그때 좀 더 구체화 해보죠

2024-08-19 14:43 UTC, merged