feature/WAG-76/setWebsocketChat
wagora-chat/wagora-chat-backend pull request #33
Opened 2024-09-09 13:33 UTC by mgstyle97

# 작업 분류

- [x] 기능 추가 (feat)
- [x] 기능 변경 (update)
- [x] 버그 수정 (fix)
- [ ] 테스트 코드 작성 (test)
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트 (chore)
- [ ] 기타 사소한 수정 (docs)

<br>

# 작업 내용 요약
- 회원의 프로필 정보에 대한 기본 처리 및 데이터 삽입 수정
- 채팅을 위한 기본 설정 및 단계별 구현(채팅방 연결, 채팅, 채팅방 연결 끊기)
- MemberNotExists 에러 발생에 대한 에러 코드 생성자 주입으로 변경

<br>

# 코드 리뷰 참고 사항
- 회원가입 로직에 대해 기본 프로필 주입 부분
- 채팅에 관한 요청 처리를 위한 부분 확인

<br>

# 관련 자료
[Jira Ticket](https://hb-wisoft.atlassian.net/browse/WAG-76?atlOrigin=eyJpIjoiOWI3MjY3NTQ3YzlkNGFhM2JmYmUwZmU1MTliNmFkMjYiLCJwIjoiaiJ9)

<br>

2024-09-09 14:55 UTC, SeoYunnn reviewed
Reviewer : @SeoYunnn 
작업량이 매우 많았을 텐데, 수고 많으셨습니다 !
리뷰 확인해주시고 수정 부탁드립니다.

2024-09-09 14:55 UTC, SeoYunnn commented on prisma/schema.prisma
> +  createdAt DateTime @default(now()) @map("created_at")
Prisma 에선 Timezone을 지원하지 않습니다.
@default(now()) 를 지정해놔도,  KST 시간(한국 표준시)이 아닌 UTC 시간(KTC - 9시간)이 저장됩니다.
만약 Database의 Timezone이 KST로 설정이 되어 있다면 다시 값을 가져올 때 UTC에 맞춰서 9시간이 더해져서 반환되기 때문에, KST 를 사용하고 있다면, 추가적인 조치가 필요할 것 같습니다.

2024-09-09 14:55 UTC, SeoYunnn commented on src/domain/auth/dto/req/signup.request.dto.ts
> +        type: BigInt,
BigInt 로 다시 지정해준 이유가 있을까요 ?

2024-09-09 14:55 UTC, SeoYunnn commented on src/domain/chat/chat.gateway.ts
> +        this.logger.log("[chat - message] finish");
채팅방 참여라든지, 메시지 전송, 방 떠나기 등 비동기 작업에서 에러 처리도 필요하지 않을까요 ?
 saveChat에서 예외가 발생하면, 에러가 클라이언트로 전달되지 않을 것 같네요.

2024-09-09 14:55 UTC, SeoYunnn commented on src/domain/chat/chat.gateway.ts
> +    async handleMessage(@MessageBody() socketMessage: SendChatMessage, @ConnectedSocket() client: SocketMember) {
handleMessage에서 채팅 메시지를 저장하기 전에 메시지의 유효성 검사를 해주는 건 어떨까요 ?
예를 들어 채팅을 아무것도 치지 않고 공백만 보냈을 경우 전송이 안되게끔 해주는 것도 있을 거 같네요.

2024-09-09 14:55 UTC, SeoYunnn commented on src/domain/chat/chat.service.ts
> +
현재 saveChat 메서드가 반환값이 없어보이는데 추후에 chat 의 결과값은 사용될 일이 없을까요 ?

2024-09-09 14:55 UTC, SeoYunnn commented on src/domain/chat/guards/websocket.jwt.guard.ts
> +            const token = authToken.split(" ")[1];
"Bearer"가 없는 토큰이 들어온다면 undefined를 반환하게 될 거 같은데, Bearer 형식 확인 후 토큰 추출을 진행하는건 어떨까요 ?

2024-09-09 14:55 UTC, SeoYunnn commented on src/domain/chat/guards/websocket.jwt.guard.ts
> +            throw new WsException("Invalid token");
이때 에러는 토큰 자체가 없거나 검증에 실패했을 때도 동일하게 "Invalid token"을 보내주게 되는데, 에러 메세지를 조금 구체화 시켜도 좋지 않을까요 ?
예를 들어, 토큰 만료, 인증 실패 등등..

2024-09-09 23:52 UTC, mgstyle97 commented on src/domain/auth/dto/req/signup.request.dto.ts
> +        type: BigInt,
file 스키마가 생김으로써 기본 프로필 경로 지정 또한 데이터베이스에 있는 파일 정보를 읽어와 지정해줘야 하기 때문에 bigint로 지정하여 기존 데이터베이스에 있는 파일 정보를 읽어와 회원에서 참조하도록 지정해줘야 하기 때문에 BigInt로 변경하였습니다.

2024-09-09 23:54 UTC, mgstyle97 commented on src/domain/chat/chat.gateway.ts
> +        this.logger.log("[chat - message] finish");
에러 발생 부분에서는 논의가 필요해 보입니다.
웹소켓 특징상 요청 및 응답의 형식이 아닌 대화 형식이기 때문에 요청을 보냈을 때 특정 사용자에게 에러 메시지만 보내면 될듯하여 현재는 에러 발생시 아무런 메시지도 전달되지 않는 형태입니다.
추가로 조치할 수 있는 부분에 있어서 조치한 뒤, 다시 커밋하도록 하겠습니다.

2024-09-09 23:55 UTC, mgstyle97 commented on src/domain/chat/chat.gateway.ts
> +    async handleMessage(@MessageBody() socketMessage: SendChatMessage, @ConnectedSocket() client: SocketMember) {
이 부분은 바로 수정하도록 하겠습니다.

2024-09-09 23:57 UTC, mgstyle97 commented on src/domain/chat/chat.service.ts
> +
기존 HTTP 로 통신하던 것과 다르게 메시지를 주고 받는 프로토콜 형식에서 메시지를 저장한 뒤의 결과를 클라이언트에 전달할 필요가 없어 결과값을 반환하지는 않았습니다.
하지만, 메서드의 처리가 올바르게 되었는지 유무를 판단하기 위해서는 결과값이 필요하다고도 생각하여 결과를 위한 id 정도는 반환되어도 된다고 생각합니다.

2024-09-09 23:57 UTC, mgstyle97 commented on src/domain/chat/guards/websocket.jwt.guard.ts
> +            const token = authToken.split(" ")[1];
이 부분도 바로 수정하도록 하겠습니다.

2024-09-09 23:57 UTC, mgstyle97 commented on src/domain/chat/guards/websocket.jwt.guard.ts
> +            throw new WsException("Invalid token");
발생되는 에러에 따라 추가 처리하도록 해보겠습니다.

2024-09-10 13:42 UTC, kukjun requested changes
@mgstyle97 

웹소켓 쪽은 테스트를 해봐도 잘 안나오는 부분이 있어서, 그 부분에 대해서는 제가 따로 테스트 해보고 말씀드리겠습니다. 고생하셨어요.

로직 원래대로 돌리는 것에 대해서 더 논의하고 싶은게 있으시면 카톡주세요. 만약 원래대로 돌리시고 말씀해주시면 Approve 하겠습니다.

2024-09-10 13:42 UTC, kukjun commented on prisma/schema.prisma
> +  Chat            Chat[]
@mgstyle97 

저번에 말했던 주제인데, 모델을 변경하는건 되게 민감한 주체인 것 같습니다. 기존 코드가 돌아가지 않는 상황이라, 해당하는 작업을 할때는 추가를 하고, 쓰이는 코드를 제거하고, 삭제하는 순서를 가지는게 맞는 것 같아요.

2024-09-10 13:42 UTC, kukjun commented on src/domain/auth/auth.service.ts
> +                fileId: fileId,
@mgstyle97 

![image](https://github.com/user-attachments/assets/e3a1f132-345e-4769-ab19-1c32b8092749)

지금과 같은 에러가 나네요. 기존 로직으로 돌려 놓는게 좋을 것 같습니다.
이유는 다음과 같습니다.

1. 파일 업로드가 실질적으로 구현되지 않아서 테스트코드는 다 깨질 것 같습니다.
2. 파일 업로드 구현 시, 변경해도 될 부분이라 지금 이 부분을 건드려서 프로그램에서 예상과 다르게 동작하는 부분을 만들어내는게 부담스러울 것 같습니다.
3. 스프린트 시작 전에 Develop PR을 해서 Main에 합치게 될텐데, 파일 업로드 기능 전까지 서버에서 회원가입을 할 수 없을 것 같습니ㅏㄷ.

2024-09-10 13:42 UTC, kukjun commented on src/domain/auth/specs/generators/signup-dto.generator.ts
> +            profile: faker.number.bigInt(),
@mgstyle97 
위에서 말했던 이슈로 인해서, 해당 작업으로도 e2e는 에러가 날 것 같습니다.

2024-09-19 01:33 UTC, kukjun approved these changes
👍

2024-09-21 08:14 UTC, merged