Feature/WAG-16/email-varification
wagora-chat/wagora-chat-backend pull request #5
Opened 2024-05-07 07:13 UTC by kukjun

# 작업 분류

- [x] 기능 추가 (feat)
- [x] 테스트 코드 작성 (test)
- [x] 의존성, 환경 변수, 빌드 관련 코드 업데이트 (chore)

<br>

# 작업 내용 요약

email로 validate code전송, validate code 확인 기능 구현과 테스트 코드 작성

<br>

# 코드 리뷰 참고 사항

논의를 해야 할 부분이 존재해서 지라티켓에 남김.
redis를 test containers를 이용했고, e2e test 진행.
errorData, errorObject의 이름을 서로 변경함. (구현상 오류)
test code 관련해서는 다들 우선작업 x. 현재 prisma를 직접 사용하는 부분이 구현사항에 없어서 작업 안함. 대신 redis 사용

<br>

# 관련 자료

[Jira Ticket](https://hb-wisoft.atlassian.net/browse/WAG-16)

<br>

2024-05-07 08:53 UTC, mgstyle97 requested changes
Reviewer: @mgstyle97 
config의 활용과 코드 리팩토링 부분에 관하여 리뷰하였습니다.

2024-05-07 08:53 UTC, mgstyle97 commented on src/app.module.ts
> +            },
@kukjun 해당 부분에 대해 Config Module을 활용하여 동적으로 정보를 삽입할 수 있는 것이 좋을거 같아요

2024-05-07 08:53 UTC, mgstyle97 commented on src/domain/auth/controller/dto/req/send-code-to-email.request.ts
> +    constructor(readonly email: string) {
@kukjun 요청 dto에 대해 validation하는 것이 좋을거 같습니다

2024-05-07 08:53 UTC, mgstyle97 commented on src/domain/auth/service/email.service.ts
> +    constructor(private readonly configService: ConfigService, @InjectRedis() private readonly client: Redis) {
@kukjun configService를 필드로 두는 것에 대해 논의가 있으면 좋겠습니다

2024-05-07 08:53 UTC, mgstyle97 commented on src/exception/http/not-found.exception.ts
> +    constructor(value: string, errorCode: ResponseCode) {
@kukjun 고정된 ResponseCode를 주입받는 다면 고정해놔도 좋을거 같습니다

2024-05-07 10:07 UTC, kukjun commented on src/app.module.ts
> +            },
네 인정합니다 ^_^

2024-05-07 10:09 UTC, kukjun commented on src/domain/auth/controller/dto/req/send-code-to-email.request.ts
> +    constructor(readonly email: string) {
기본 validation을 적용할게요

2024-05-07 10:13 UTC, kukjun commented on src/domain/auth/service/email.service.ts
> +    constructor(private readonly configService: ConfigService, @InjectRedis() private readonly client: Redis) {
생성자 주입을 안하는 형태로 변경

2024-05-07 10:13 UTC, kukjun commented on src/domain/auth/service/email.service.ts
> +    constructor(private readonly configService: ConfigService, @InjectRedis() private readonly client: Redis) {
필드로 두는게 좋아보이네요.

2024-05-07 13:11 UTC, kukjun commented on src/exception/http/not-found.exception.ts
> +    constructor(value: string, errorCode: ResponseCode) {
@mgstyle97 이 부분이 논의되는 부분인 것 같네요. 같은 예외에도 다른 ErrorCode가 발생할 수 있는가를 생각해봐야 하지 않을까요?

저번에, 같은 상황에도 다른 예외 코드가 발생될 수 있다는 요구사항에 따른 작업내용입니다.

2024-05-11 02:12 UTC, mgstyle97 approved these changes
Reviewer: @mgstyle97 
좋습니다! 합쳐도 될거 같아요

2024-05-11 02:53 UTC, merged